# Generated by Django 4.2.29 on 2026-04-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_userprofile_organization_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="mail_id",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
