# Generated by Django 4.2.29 on 2026-04-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userprofile_mail_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="full_address",
            field=models.TextField(
                blank=True, help_text="Combined address, city, state, country"
            ),
        ),
    ]
