# Generated by Django 4.2.29 on 2026-04-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_userprofile_full_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="pincode",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
