# Generated by Django 5.1.15 on 2026-04-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="last_matched_vendors",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="last_rfq_vendors",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
