# Generated by Django 5.1.15 on 2026-04-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_project_project_password_quotation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="lead_time_days",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
