# Generated by Django 5.1.15 on 2026-04-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_quotation_count_alter_quotation_lead_time_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="rfq_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
