# Generated by Django 5.1.15 on 2026-04-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_project_rfq_deadline"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="rfq_deadline",
        ),
        migrations.AddField(
            model_name="quotation",
            name="submission_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
