# Generated by Django 5.1.15 on 2026-04-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_remove_project_rfq_deadline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotation",
            name="bom_item_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
