# Generated by Django 5.1.15 on 2026-04-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0007_alter_quotation_bom_item_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectvendoraccess",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
