# Generated by Django 4.2.29 on 2026-04-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0008_projectvendoraccess_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="company_id",
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name="quotation",
            name="company_id",
            field=models.IntegerField(db_index=True, default=1),
        ),
    ]
