# Generated by Django 4.2.29 on 2026-04-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0009_project_company_id_quotation_company_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="shipment_from_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
