# Generated by Django 4.2.29 on 2026-04-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0010_quotation_shipment_from_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="part_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="quotation",
            name="size_spec",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
