# Generated by Django 4.2.29 on 2026-04-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0011_quotation_part_name_quotation_size_spec"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="quotation",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="quotation",
            name="negotiation_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="shipment_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="quotation",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
