# Generated by Django 4.2.29 on 2026-04-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0012_quotation_city_quotation_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="distance_to_organization_km",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
