# Generated by Django 4.2.29 on 2026-04-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0013_quotation_distance_to_organization_km_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="po_issued",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quotation",
            name="po_issued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
