# Generated by Django 4.2.29 on 2026-04-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0014_quotation_po_issued_quotation_po_issued_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="organization",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
