# Generated by Django 4.2.29 on 2026-04-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0015_project_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="organization",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
