# Generated by Django 4.2.29 on 2026-03-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bom_id', models.CharField(db_index=True, help_text='BOM identifier', max_length=100)),
                ('material', models.CharField(help_text='Material description or code', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, help_text='Required quantity', max_digits=15)),
                ('date_of_requirement', models.DateField(blank=True, help_text='Date when material is required', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_file', models.CharField(blank=True, help_text='Original filename', max_length=255)),
            ],
            options={
                'verbose_name': 'BOM Line',
                'verbose_name_plural': 'BOM Lines',
                'db_table': 'bom',
                'ordering': ['-created_at', 'bom_id', 'material'],
            },
        ),
    ]
