# Generated by Django 4.2.29 on 2026-03-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='part_number',
            field=models.CharField(blank=True, help_text='Part numbers from the file', max_length=100),
        ),
    ]
