# Generated by Django 5.1.15 on 2026-04-02 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bom", "0002_bom_part_number"),
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bom",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bom_lines",
                to="project.project",
            ),
        ),
    ]
