# Generated by Django 4.2.29 on 2026-04-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bom", "0003_bom_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="bom",
            name="company_id",
            field=models.IntegerField(db_index=True, default=1),
        ),
    ]
