# Generated by Django 4.2.29 on 2026-04-08 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0009_project_company_id_quotation_company_id"),
        ("bom", "0004_bom_company_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="bom",
            name="selected_quotation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirmed_on_bom",
                to="project.quotation",
            ),
        ),
    ]
