# Generated by Django 4.2.29 on 2026-04-09 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bom", "0005_bom_selected_quotation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bom",
            options={
                "ordering": ["-created_at", "material"],
                "verbose_name": "BOM Line",
                "verbose_name_plural": "BOM Lines",
            },
        ),
        migrations.RemoveField(
            model_name="bom",
            name="bom_id",
        ),
    ]
