# Generated by Django 4.2.29 on 2026-04-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bom", "0006_alter_bom_options_remove_bom_bom_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="bom",
            name="Group_name",
            field=models.CharField(
                blank=True, help_text="BOM Group/material Group", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="bom",
            name="length_area",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Length or area quantity based on part",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="bom",
            name="part",
            field=models.CharField(
                blank=True, help_text="BOM part/type", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="bom",
            name="size",
            field=models.CharField(blank=True, help_text="BOM size", max_length=100),
        ),
    ]
