# Generated by Django 4.2.29 on 2026-04-16 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bom", "0007_bom_group_name_bom_length_area_bom_part_bom_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="bom",
            name="quantity_type",
            field=models.CharField(
                blank=True,
                help_text="Type of quantity (Area, Length, Count)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="bom",
            name="unit",
            field=models.CharField(
                blank=True, help_text="Unit of measurement", max_length=50
            ),
        ),
    ]
