# Generated by Django 4.2.29 on 2026-04-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bom", "0008_bom_quantity_type_bom_unit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bom",
            name="Group_name",
        ),
        migrations.AddField(
            model_name="bom",
            name="grade_name",
            field=models.CharField(
                blank=True, help_text="BOM Grade/material Grade", max_length=255
            ),
        ),
    ]
