# Generated by Django 4.2.29 on 2026-04-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bom", "0009_remove_bom_group_name_bom_grade_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part", models.CharField(db_index=True, max_length=100, unique=True)),
                ("part_name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "part_master",
            },
        ),
        migrations.AddField(
            model_name="bom",
            name="category",
            field=models.CharField(
                blank=True,
                help_text="Part category (e.g. STEEL, BOLT/NUT)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bom",
            name="part_name",
            field=models.CharField(
                blank=True,
                help_text="Full name (e.g. WELDED STEEL)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bom",
            name="part",
            field=models.CharField(
                blank=True, help_text="BOM part/type (e.g. WS, C, L)", max_length=100
            ),
        ),
    ]
