# Generated by Django 4.2.29 on 2026-04-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bom", "0010_partmaster_bom_category_bom_part_name_alter_bom_part"),
    ]

    operations = [
        migrations.AddField(
            model_name="bom",
            name="po_issued",
            field=models.BooleanField(default=False),
        ),
    ]
